on:
    push:
      branches:
        - main
jobs:
    hello_world_job:
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
        - uses: actions/checkout@v4
        - name: Run Custom Action
          uses: /home/z390/Bureau/action-personnalise-workflows/actions/action.yml
          with:
            who-to-greet: 'Mona the Octocat'
        - run: echo random-number ${{ steps.foo.outputs.random-number }}
          shell: bash