on:
    push:
      branches:
        - main
jobs:
    hello_world_job:
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Build and Push Docker Image
          run: docker build -t action-personnalise-workflows .

        - name: Run Custom Action
          uses: ./action-personnalise-workflows/action.yml
          with:
            who-to-greet: 'Mona the Octocat'
  
        - name: Show Random Number
          run: echo random-number ${{ steps.foo.outputs.random-number }}
          shell: bash

        - name: Set up Docker Build
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.DOCKER_TOKEN }}
           
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v5
          with:
            context: ./action-personnalise-workflows
            push: true
            tags: |
                ghcr.io/katarzyna-da-silva/action-personnalise-workflows:latest